default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>

development:
  <<: *default
  database: genre_quiz_development

test:
  <<: *default
  database: genre_quiz_test

production:
  <<: *default
  database: genre_quiz_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

